-- Acme Orders: synthetic Oracle schema used as the demo source system
-- (all data and names are fictional)

CREATE SEQUENCE SEQ_ORDER_ID START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CUSTOMER_ID START WITH 1 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE SEQ_AUDIT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID     NUMBER(10)      PRIMARY KEY,
    FULL_NAME       VARCHAR2(120)   NOT NULL,
    EMAIL           VARCHAR2(200),
    PHONE           VARCHAR2(30),
    REGION_CODE     VARCHAR2(5),
    CREDIT_LIMIT    NUMBER(12,2)    DEFAULT 0,
    STATUS_FLAG     CHAR(1)         DEFAULT 'A',
    CREATED_ON      DATE            DEFAULT SYSDATE,
    LAST_LOGIN      TIMESTAMP
);

CREATE TABLE REGIONS (
    REGION_CODE     VARCHAR2(5)     PRIMARY KEY,
    REGION_NAME     VARCHAR2(60)    NOT NULL,
    MANAGER_ID      NUMBER(10)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID     NUMBER(10)      PRIMARY KEY,
    FULL_NAME       VARCHAR2(120)   NOT NULL,
    MANAGER_ID      NUMBER(10),
    DEPARTMENT      VARCHAR2(60),
    SALARY          NUMBER(12,2),
    HIRE_DATE       DATE
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID      NUMBER(10)      PRIMARY KEY,
    PRODUCT_NAME    VARCHAR2(150)   NOT NULL,
    CATEGORY        VARCHAR2(60),
    UNIT_PRICE      NUMBER(10,2),
    STOCK_QTY       NUMBER(8)       DEFAULT 0
);

CREATE TABLE ORDERS (
    ORDER_ID        NUMBER(12)      PRIMARY KEY,
    CUSTOMER_ID     NUMBER(10)      NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
    ORDER_DATE      DATE            DEFAULT SYSDATE,
    STATUS          VARCHAR2(20),
    TOTAL_AMOUNT    NUMBER(14,2),
    DISCOUNT_PCT    NUMBER(5,2),
    NOTES           VARCHAR2(500)
);

CREATE TABLE ORDER_ITEMS (
    ORDER_ID        NUMBER(12)      NOT NULL REFERENCES ORDERS(ORDER_ID),
    LINE_NO         NUMBER(4)       NOT NULL,
    PRODUCT_ID      NUMBER(10)      NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY        NUMBER(6)       NOT NULL,
    UNIT_PRICE      NUMBER(10,2)    NOT NULL,
    PRIMARY KEY (ORDER_ID, LINE_NO)
);

CREATE TABLE AUDIT_LOG (
    AUDIT_ID        NUMBER(12)      PRIMARY KEY,
    TABLE_NAME      VARCHAR2(40),
    ACTION          VARCHAR2(10),
    ACTION_TS       TIMESTAMP DEFAULT SYSTIMESTAMP,
    DETAILS         CLOB
);

CREATE INDEX IDX_ORDERS_CUST_DATE ON ORDERS (CUSTOMER_ID, ORDER_DATE);
CREATE INDEX IDX_CUSTOMERS_REGION ON CUSTOMERS (REGION_CODE);
